---
name: terraform-prod
"on":
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute plan digest
        run: echo "PLAN_DIGEST=sha256:deadbeef" >> $GITHUB_ENV

      - name: Relia authorize for prod apply
        id: relia
        uses: ./.github/actions/relia-authorize
        with:
          relia_url: ${{ secrets.RELIA_URL }}
          action: terraform.apply
          resource: aws:account:123456789012:stack/prod
          env: prod
          intent_json: >
            {"change_id":"CHG-1234","ticket":"JIRA-555","reason":"Apply approved infra change"}
          plan_digest: ${{ env.PLAN_DIGEST }}
          diff_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Sanity check AWS creds
        run: |
          test -n "${AWS_ACCESS_KEY_ID:-}"
          test -n "${AWS_SECRET_ACCESS_KEY:-}"
          test -n "${AWS_SESSION_TOKEN:-}"
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
          if [[ "${AWS_ACCESS_KEY_ID}" == DEV_* ]]; then
            echo "got dev placeholder creds; set RELIA_AWS_MODE=real on the gateway + configure AWS OIDC trust" >&2
            exit 1
          fi
          echo "Relia verify: ${{ secrets.RELIA_URL }}/verify/${{ steps.relia.outputs.receipt_id }}"
          aws sts get-caller-identity

      - name: Terraform apply (now has short-lived creds)
        run: |
          terraform init
          terraform apply -auto-approve
