from relia.utils.output import generate_html_report
from relia.models import ReliaResource
from relia import __version__


def test_html_contains_version():
    resources = []
    costs = {}
    html = generate_html_report(resources, costs)

    # Check for version from package
    assert f"v{__version__}" in html
    assert "Generated by Relia OSS" in html


def test_html_structure_with_data():
    r1 = ReliaResource(
        resource_type="aws_instance",
        resource_name="web",
        attributes={"instance_type": "t3.micro"},
        file_path="main.tf",
        suggestions=["Upgrade to t4g"],
    )
    costs = {"aws_instance.web": 12.50}

    html = generate_html_report([r1], costs)

    # Check for resource ID
    assert "aws_instance.web" in html
    # Check for cost formatting
    assert "$12.50" in html
    # Check for tip presence
    assert "💡 Upgrade to t4g" in html
    # Check for mermaid graph
    assert "mermaid" in html
    assert "aws_instance" in html
    assert "fill:#fecaca" not in html  # Under 50, no red alert style


def test_html_over_budget_visuals():
    # Only checks if CSS class/color logic triggers string presence
    # Implementation uses inline styles or classes?
    # Let's check status text

    html = generate_html_report([], {}, budget=100.0)
    assert "Within Budget" in html

    # Empty costs = 0 < 100

    # Now over budget
    costs = {"r1": 200.0}
    html_fail = generate_html_report([], costs, budget=100.0)
    assert "Over Budget" in html_fail
    assert "#dc2626" in html_fail  # Red color code
